apiVersion: v1
kind: ConfigMap
metadata:
  name: ordersphere-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:h2:file:./data/ordersphere-db"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_H2_CONSOLE_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"