apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersphere
  template:
    metadata:
      labels:
        app: ordersphere
    spec:
      containers:
        - name: ordersphere
          image: ordersphere:0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
